services:
  postgres:
    image: "bitnami/postgresql"
    container_name: "anuncia-ai"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=anunciadb
